"""Table Designer Service: DDL generation and Diff migration engine.
Supports SQL Server and PostgreSQL.
"""
from typing import Any, Dict, List


class TableDesignerService:

    @staticmethod
    def _quote_ident(name: str, engine: str) -> str:
        clean = (name or "").strip()
        if engine == "postgresql":
            if clean.startswith('"') and clean.endswith('"'):
                return clean
            return f'"{clean}"'
        else:
            if clean.startswith('[') and clean.endswith(']'):
                return clean
            return f'[{clean}]'

    @staticmethod
    def _format_table_name(schema: str, table: str, engine: str) -> str:
        q_schema = TableDesignerService._quote_ident(schema or ("public" if engine == "postgresql" else "dbo"), engine)
        q_table = TableDesignerService._quote_ident(table, engine)
        return f"{q_schema}.{q_table}"

    @classmethod
    def format_column_type(cls, col: Dict[str, Any], engine: str) -> str:
        raw_type = (col.get("type") or "varchar").strip()
        t = raw_type.lower()
        size = str(col.get("size") or "").strip()
        scale = str(col.get("scale") or "").strip()

        # Sizes for char/varchar/nvarchar/varbinary
        if t in ("varchar", "nvarchar", "char", "nchar", "varbinary", "binary"):
            if size.lower() == "max":
                return f"{t}(max)"
            elif size.isdigit():
                return f"{t}({size})"
            return t

        # Numeric / Decimal
        if t in ("decimal", "numeric"):
            if size.isdigit() and scale.isdigit() and int(scale) > 0:
                return f"{t}({size}, {scale})"
            elif size.isdigit():
                return f"{t}({size})"
            return t

        if t in ("datetime2", "time") and scale.isdigit():
            return f"{t}({scale})"

        # If it's a UDT or custom type, preserve raw casing!
        if "." in raw_type or "[" in raw_type or '"' in raw_type or t not in (
            "bigint", "binary", "bit", "char", "date", "datetime", "datetime2",
            "datetimeoffset", "decimal", "float", "image", "int", "money",
            "nchar", "ntext", "numeric", "nvarchar", "real", "smalldatetime",
            "smallint", "smallmoney", "text", "time", "tinyint", "uniqueidentifier",
            "varbinary", "varchar", "xml", "serial", "bigserial", "smallserial",
            "boolean", "bytea", "double precision", "integer", "json", "jsonb",
            "timestamptz", "timetz", "uuid"
        ):
            return raw_type

        return t

    @classmethod
    def generate_column_def(cls, col: Dict[str, Any], engine: str) -> str:
        q_col = cls._quote_ident(col.get("name", ""), engine)
        type_str = cls.format_column_type(col, engine)
        parts = [q_col, type_str]

        # Base type check for string vs numeric
        base_type = (col.get("type") or "").strip().lower()
        is_char_type = base_type in ("varchar", "nvarchar", "char", "nchar", "text", "ntext")
        is_numeric_type = base_type in (
            "int", "bigint", "smallint", "tinyint", "decimal", "numeric",
            "float", "real", "bit", "money", "smallmoney", "integer"
        )

        # Collation - Only valid for standard character string data types in SQL Server / PostgreSQL
        # COLLATE clause cannot be used on user-defined data types (SQL Server Error 452) or non-string types
        collation = (col.get("collation") or "").strip()
        if collation and collation != "DATABASE_DEFAULT" and collation.lower() != "default" and is_char_type:
            if engine == "sqlserver":
                parts.append(f"COLLATE {collation}")
            else:
                parts.append(f'COLLATE "{collation}"')

        # Sequence or Identity / Auto-increment
        seq_name = (col.get("sequence_name") or "").strip()
        if seq_name:
            if engine == "sqlserver":
                parts.append(f"DEFAULT (NEXT VALUE FOR {seq_name})")
            else:
                parts.append(f"DEFAULT nextval('{seq_name}')")
        elif col.get("is_identity"):
            seed = col.get("identity_seed", 1)
            inc = col.get("identity_increment", 1)
            if engine == "sqlserver":
                parts.append(f"IDENTITY({seed},{inc})")
            elif engine == "postgresql" and type_str not in ("serial", "bigserial", "smallserial"):
                parts.append(f"GENERATED BY DEFAULT AS IDENTITY (START WITH {seed} INCREMENT BY {inc})")

        # Default (if not using sequence)
        default_val = (col.get("default_value") or "").strip()
        if default_val and not seq_name:
            if is_numeric_type:
                cleaned_def = default_val
                if "::" in cleaned_def:
                    cleaned_def = cleaned_def.split("::")[0].strip()
                while (cleaned_def.startswith("'") and cleaned_def.endswith("'")) or (cleaned_def.startswith('"') and cleaned_def.endswith('"')):
                    cleaned_def = cleaned_def[1:-1].strip()
                default_val = cleaned_def
            parts.append(f"DEFAULT {default_val}")

        # Nullability
        if col.get("is_pk") or not col.get("nullable", True):
            parts.append("NOT NULL")
        else:
            parts.append("NULL")

        return " ".join(parts)

    @classmethod
    def generate_create_table_statements(cls, metadata: Dict[str, Any]) -> List[str]:
        engine = metadata.get("engine", "sqlserver")
        schema = metadata.get("schema") or ("public" if engine == "postgresql" else "dbo")
        table = metadata.get("table") or "Untitled"
        tbl_name = cls._format_table_name(schema, table, engine)

        columns = metadata.get("columns", [])
        indexes = metadata.get("indexes", [])
        fks = metadata.get("foreign_keys", [])
        uniques = metadata.get("uniques", [])
        checks = metadata.get("checks", [])
        triggers = metadata.get("triggers", [])

        lines = []
        has_clustered_index = False

        # 1. Column definitions
        for col in columns:
            lines.append("    " + cls.generate_column_def(col, engine))

        # 2. Primary Key
        pk_cols = [col["name"] for col in columns if col.get("is_pk")]
        if pk_cols:
            q_pk_cols = ", ".join(cls._quote_ident(c, engine) for c in pk_cols)
            pk_name = cls._quote_ident(f"PK_{table}", engine)
            if engine == "sqlserver":
                lines.append(f"    CONSTRAINT {pk_name} PRIMARY KEY CLUSTERED ({q_pk_cols})")
                has_clustered_index = True
            else:
                lines.append(f"    CONSTRAINT {pk_name} PRIMARY KEY ({q_pk_cols})")

        # 3. Unique Constraints
        # In SQL Server, cannot add more than one clustered index (SQL Server Error 8112)
        for uq in uniques:
            uq_name = cls._quote_ident(uq.get("name") or f"UQ_{table}", engine)
            uq_cols = ", ".join(cls._quote_ident(c, engine) for c in uq.get("fields", []))
            if uq_cols:
                is_clustered = bool(uq.get("is_clustered")) and not has_clustered_index and (engine == "sqlserver")
                if is_clustered:
                    has_clustered_index = True
                clustered = " CLUSTERED" if is_clustered else ""
                lines.append(f"    CONSTRAINT {uq_name} UNIQUE{clustered} ({uq_cols})")

        # 4. Check Constraints
        for chk in checks:
            chk_name = cls._quote_ident(chk.get("name") or f"CK_{table}", engine)
            clause = chk.get("check_clause", "")
            if clause:
                lines.append(f"    CONSTRAINT {chk_name} CHECK ({clause})")

        # 5. Foreign Key Constraints
        for fk in fks:
            fk_name = cls._quote_ident(fk.get("name") or f"FK_{table}", engine)
            local_cols = ", ".join(cls._quote_ident(c, engine) for c in fk.get("fields", []))
            ref_schema = fk.get("ref_schema") or schema
            ref_tbl = fk.get("ref_table", "")
            ref_cols = ", ".join(cls._quote_ident(c, engine) for c in fk.get("ref_fields", []))
            if local_cols and ref_tbl and ref_cols:
                ref_full = cls._format_table_name(ref_schema, ref_tbl, engine)
                fk_line = f"    CONSTRAINT {fk_name} FOREIGN KEY ({local_cols}) REFERENCES {ref_full} ({ref_cols})"
                on_del = fk.get("on_delete")
                if on_del and on_del.upper() != "NO ACTION":
                    fk_line += f" ON DELETE {on_del.upper()}"
                on_upd = fk.get("on_update")
                if on_upd and on_upd.upper() != "NO ACTION":
                    fk_line += f" ON UPDATE {on_upd.upper()}"
                lines.append(fk_line)

        body = ",\n".join(lines)
        stmts = [f"CREATE TABLE {tbl_name} (\n{body}\n);"]

        # Supplementary Statements: Standalone Indexes
        for idx in indexes:
            idx_name = cls._quote_ident(idx.get("name") or f"IX_{table}", engine)
            fields = idx.get("fields", [])
            if not fields:
                continue
            idx_cols = []
            for f in fields:
                if isinstance(f, dict):
                    col_str = cls._quote_ident(f["column"], engine)
                    if f.get("desc"):
                        col_str += " DESC"
                    idx_cols.append(col_str)
                else:
                    idx_cols.append(cls._quote_ident(str(f), engine))

            unique_str = "UNIQUE " if idx.get("is_unique") else ""
            if engine == "sqlserver":
                raw_itype = (idx.get("index_type") or "NONCLUSTERED").upper()
                if raw_itype == "CLUSTERED":
                    if has_clustered_index:
                        itype = "NONCLUSTERED"
                    else:
                        itype = "CLUSTERED"
                        has_clustered_index = True
                else:
                    itype = raw_itype
                stmts.append(
                    f"CREATE {unique_str}{itype} INDEX {idx_name} ON {tbl_name} ({', '.join(idx_cols)});"
                )
            else:
                itype = idx.get("index_type") or "BTREE"
                stmts.append(
                    f"CREATE {unique_str}INDEX {idx_name} ON {tbl_name} USING {itype.lower()} ({', '.join(idx_cols)});"
                )

        # Supplementary Statements: Triggers
        for tr in triggers:
            t_def = (tr.get("definition") or "").strip()
            if t_def:
                stmts.append(t_def)

        return stmts

    @classmethod
    def generate_create_table_ddl(cls, metadata: Dict[str, Any]) -> str:
        stmts = cls.generate_create_table_statements(metadata)
        engine = metadata.get("engine", "sqlserver")
        if not stmts:
            return ""
        if engine == "sqlserver":
            return "\n\nGO\n\n".join(stmts) + "\n\nGO\n"
        return "\n\n".join(stmts) + "\n"

    @classmethod
    def generate_diff(cls, original: Dict[str, Any], modified: Dict[str, Any]) -> Dict[str, Any]:
        """Calculates differences between original schema and modified schema.
        Returns statements, full migration SQL, and warnings for destructive changes.
        """
        engine = modified.get("engine") or (original and original.get("engine")) or "sqlserver"
        schema = modified.get("schema") or (original and original.get("schema")) or ("public" if engine == "postgresql" else "dbo")
        table = modified.get("table") or (original and original.get("table")) or "Untitled"
        tbl_name = cls._format_table_name(schema, table, engine)

        # Clean unquoted table identifier for alter table statements
        if engine == "postgresql":
            clean_tbl = table.strip('"')
            clean_sch = (schema or "public").strip('"')
            if clean_sch and clean_sch.lower() != "public":
                alt_tbl_name = f"{clean_sch}.{clean_tbl}"
            else:
                alt_tbl_name = clean_tbl
        else:
            clean_tbl = table.strip('[]')
            clean_sch = (schema or "dbo").strip('[]')
            if clean_sch and clean_sch.lower() != "dbo":
                alt_tbl_name = f"{clean_sch}.{clean_tbl}"
            else:
                alt_tbl_name = clean_tbl

        statements = []
        warnings = []

        # Check if creating a brand new table
        if not original or not original.get("columns"):
            new_stmts = cls.generate_create_table_statements(modified)
            for s in new_stmts:
                if s.startswith("CREATE TABLE"):
                    category = "tables"
                    desc = "Create table and columns"
                elif " INDEX " in s:
                    category = "indexes"
                    desc = "Create index"
                elif s.startswith("CREATE TRIGGER") or s.startswith("CREATE OR REPLACE TRIGGER"):
                    category = "triggers"
                    desc = "Create trigger"
                elif "FOREIGN KEY" in s:
                    category = "constraints"
                    desc = "Create foreign key"
                else:
                    category = "constraints"
                    desc = "Create constraint"
                statements.append({
                    "sql": s,
                    "destructive": False,
                    "description": desc,
                    "type": category
                })
            join_sep = "\n\nGO\n\n" if engine == "sqlserver" else "\n\n"
            mig_sql = join_sep.join(new_stmts)
            if engine == "sqlserver" and mig_sql.strip():
                mig_sql += "\n\nGO\n"
            elif mig_sql.strip():
                mig_sql += "\n"
            return {
                "statements": statements,
                "migration_sql": mig_sql,
                "has_destructive": False,
                "warnings": []
            }

        orig_cols = {c["name"]: c for c in original.get("columns", [])}
        mod_cols = {c["name"]: c for c in modified.get("columns", [])}

        # 0. Table Rename
        orig_tbl_raw = str(original.get("table") or "").strip().strip('\"[]')
        mod_tbl_raw = str(modified.get("table") or "").strip().strip('\"[]')
        if orig_tbl_raw and mod_tbl_raw and orig_tbl_raw.lower() != mod_tbl_raw.lower():
            if engine == "sqlserver":
                rename_sql = f"EXEC sp_rename @objname = N'[{clean_sch}].[{orig_tbl_raw}]', @newname = N'{mod_tbl_raw}', @objtype = N'OBJECT';"
            else:
                rename_sql = f'ALTER TABLE "{clean_sch}"."{orig_tbl_raw}" RENAME TO "{mod_tbl_raw}";'
            statements.append({
                "sql": rename_sql,
                "destructive": False,
                "description": f"Rename table from {orig_tbl_raw} to {mod_tbl_raw}",
                "type": "tables"
            })

        # Track clustered index state in SQL Server (Error 8112 prevention)
        has_clustered = False
        if engine == "sqlserver":
            has_clustered = any(c.get("is_pk") for c in modified.get("columns", []))

        # 1. Dropped Columns (Destructive)
        for col_name, ocol in orig_cols.items():
            if col_name not in mod_cols:
                clean_col = col_name.strip('\"[]')
                sql = f"alter table {alt_tbl_name}\n    drop column {clean_col};"
                statements.append({
                    "sql": sql,
                    "destructive": True,
                    "description": f"Drop column {clean_col}",
                    "type": "tables"
                })
                warnings.append(f"Column {clean_col} will be dropped and its data permanently deleted.")

        # 2. Added Columns (Formatted per user sample: alter table <table>\n    add <column_name> <type>;)
        for col_name, mcol in mod_cols.items():
            if col_name not in orig_cols:
                clean_col = col_name.strip('\"[]')
                type_str = cls.format_column_type(mcol, engine).lower()
                
                parts = [f"    add {clean_col} {type_str}"]
                default_val = (mcol.get("default_value") or "").strip()
                if default_val:
                    parts.append(f"default {default_val}")
                if mcol.get("is_pk") or not mcol.get("nullable", True):
                    parts.append("not null")

                sql = f"alter table {alt_tbl_name}\n{' '.join(parts)};"
                statements.append({
                    "sql": sql,
                    "destructive": False,
                    "description": f"Add column {clean_col}",
                    "type": "tables"
                })

        # 3. Modified Columns
        for col_name, mcol in mod_cols.items():
            if col_name in orig_cols:
                ocol = orig_cols[col_name]
                # Check for changes in type, size, scale, nullability, default
                type_changed = (mcol.get("type") != ocol.get("type")) or (str(mcol.get("size")) != str(ocol.get("size"))) or (str(mcol.get("scale")) != str(ocol.get("scale")))
                null_changed = (bool(mcol.get("nullable")) != bool(ocol.get("nullable")))
                def_changed = (str(mcol.get("default_value")).strip() != str(ocol.get("default_value")).strip())

                clean_col = col_name.strip('\"[]')
                if type_changed or null_changed:
                    if engine == "sqlserver":
                        type_str = cls.format_column_type(mcol, engine).lower()
                        null_str = "null" if mcol.get("nullable", True) else "not null"
                        sql = f"alter table {alt_tbl_name}\n    alter column {clean_col} {type_str} {null_str};"
                        statements.append({
                            "sql": sql,
                            "destructive": False,
                            "description": f"Alter column {clean_col} type/nullability",
                            "type": "tables"
                        })
                    else:
                        type_str = cls.format_column_type(mcol, engine).lower()
                        if type_changed:
                            sql = f"alter table {alt_tbl_name}\n    alter column {clean_col} type {type_str} using {clean_col}::{type_str};"
                            statements.append({
                                "sql": sql,
                                "destructive": False,
                                "description": f"Alter column {clean_col} data type to {type_str}",
                                "type": "tables"
                            })
                        if null_changed:
                            null_action = "drop not null" if mcol.get("nullable", True) else "set not null"
                            sql = f"alter table {alt_tbl_name}\n    alter column {clean_col} {null_action};"
                            statements.append({
                                "sql": sql,
                                "destructive": False,
                                "description": f"Alter column {clean_col} nullability",
                                "type": "tables"
                            })

                if def_changed:
                    new_def = str(mcol.get("default_value") or "").strip()
                    mtype = (mcol.get("type") or "").strip().lower()
                    if mtype in ("int", "bigint", "smallint", "tinyint", "decimal", "numeric", "float", "real", "bit", "money", "smallmoney", "integer"):
                        if "::" in new_def:
                            new_def = new_def.split("::")[0].strip()
                        while (new_def.startswith("'") and new_def.endswith("'")) or (new_def.startswith('"') and new_def.endswith('"')):
                            new_def = new_def[1:-1].strip()

                    if engine == "sqlserver":
                        if new_def:
                            df_name = cls._quote_ident(f"DF_{clean_tbl}_{clean_col}", engine)
                            statements.append({
                                "sql": f"alter table {alt_tbl_name}\n    add constraint {df_name} default {new_def} for {clean_col};",
                                "destructive": False,
                                "description": f"Set default value for {clean_col}",
                                "type": "tables"
                            })
                    else:
                        if new_def:
                            sql = f"alter table {alt_tbl_name}\n    alter column {clean_col} set default {new_def};"
                        else:
                            sql = f"alter table {alt_tbl_name}\n    alter column {clean_col} drop default;"
                        statements.append({
                            "sql": sql,
                            "destructive": False,
                            "description": f"Change default value for {clean_col}",
                            "type": "tables"
                        })

        # 4. Primary Key Changes
        orig_pk = [c["name"] for c in original.get("columns", []) if c.get("is_pk")]
        mod_pk = [c["name"] for c in modified.get("columns", []) if c.get("is_pk")]
        if set(orig_pk) != set(mod_pk):
            pk_name = cls._quote_ident(f"PK_{table}", engine)
            if orig_pk:
                statements.append({
                    "sql": f"alter table {alt_tbl_name}\n    drop constraint {pk_name};",
                    "destructive": True,
                    "description": f"Drop primary key {pk_name}",
                    "type": "constraints"
                })
                warnings.append("Primary key constraint will be dropped and recreated.")
            if mod_pk:
                q_cols = ", ".join(cls._quote_ident(c, engine) for c in mod_pk)
                clustered = " CLUSTERED" if engine == "sqlserver" else ""
                statements.append({
                    "sql": f"alter table {alt_tbl_name}\n    add constraint {pk_name} primary key{clustered} ({q_cols});",
                    "destructive": False,
                    "description": f"Add primary key on ({q_cols})",
                    "type": "constraints"
                })

        # 5. Unique Constraints Diff
        orig_uqs = {u["name"]: u for u in original.get("uniques", [])}
        mod_uqs = {u["name"]: u for u in modified.get("uniques", [])}
        for u_name in orig_uqs:
            if u_name not in mod_uqs:
                q_uq = cls._quote_ident(u_name, engine)
                statements.append({
                    "sql": f"alter table {alt_tbl_name}\n    drop constraint {q_uq};",
                    "destructive": True,
                    "description": f"Drop unique constraint {q_uq}",
                    "type": "constraints"
                })
        for u_name, uq in mod_uqs.items():
            if u_name not in orig_uqs:
                q_uq = cls._quote_ident(u_name, engine)
                cols = ", ".join(cls._quote_ident(c, engine) for c in uq.get("fields", []))
                is_clustered = bool(uq.get("is_clustered")) and not has_clustered and (engine == "sqlserver")
                if is_clustered:
                    has_clustered = True
                clustered = " CLUSTERED" if is_clustered else ""
                statements.append({
                    "sql": f"alter table {alt_tbl_name}\n    add constraint {q_uq} unique{clustered} ({cols});",
                    "destructive": False,
                    "description": f"Add unique constraint {q_uq}",
                    "type": "constraints"
                })

        # 6. Check Constraints Diff
        orig_chks = {c["name"]: c for c in original.get("checks", [])}
        mod_chks = {c["name"]: c for c in modified.get("checks", [])}
        for c_name in orig_chks:
            if c_name not in mod_chks:
                q_chk = cls._quote_ident(c_name, engine)
                statements.append({
                    "sql": f"alter table {alt_tbl_name}\n    drop constraint {q_chk};",
                    "destructive": True,
                    "description": f"Drop check constraint {q_chk}",
                    "type": "constraints"
                })
        for c_name, chk in mod_chks.items():
            if c_name not in orig_chks:
                q_chk = cls._quote_ident(c_name, engine)
                clause = chk.get("check_clause", "")
                if clause:
                    statements.append({
                        "sql": f"alter table {alt_tbl_name}\n    add constraint {q_chk} check ({clause});",
                        "destructive": False,
                        "description": f"Add check constraint {q_chk}",
                        "type": "constraints"
                    })

        # 7. Foreign Keys Diff
        orig_fks = {f["name"]: f for f in original.get("foreign_keys", [])}
        mod_fks = {f["name"]: f for f in modified.get("foreign_keys", [])}
        for f_name in orig_fks:
            if f_name not in mod_fks:
                q_fk = cls._quote_ident(f_name, engine)
                statements.append({
                    "sql": f"alter table {alt_tbl_name}\n    drop constraint {q_fk};",
                    "destructive": True,
                    "description": f"Drop foreign key constraint {q_fk}",
                    "type": "constraints"
                })
        for f_name, fk in mod_fks.items():
            if f_name not in orig_fks:
                q_fk = cls._quote_ident(f_name, engine)
                local_cols = ", ".join(cls._quote_ident(c, engine) for c in fk.get("fields", []))
                ref_schema = fk.get("ref_schema") or schema
                ref_tbl = fk.get("ref_table", "")
                ref_cols = ", ".join(cls._quote_ident(c, engine) for c in fk.get("ref_fields", []))
                ref_full = cls._format_table_name(ref_schema, ref_tbl, engine)
                fk_sql = f"alter table {alt_tbl_name}\n    add constraint {q_fk} foreign key ({local_cols}) references {ref_full} ({ref_cols})"
                if fk.get("on_delete") and fk["on_delete"].upper() != "NO ACTION":
                    fk_sql += f" on delete {fk['on_delete'].lower()}"
                if fk.get("on_update") and fk["on_update"].upper() != "NO ACTION":
                    fk_sql += f" on update {fk['on_update'].lower()}"
                fk_sql += ";"
                statements.append({
                    "sql": fk_sql,
                    "destructive": False,
                    "description": f"Add foreign key {q_fk}",
                    "type": "constraints"
                })

        # 8. Indexes Diff
        orig_idxs = {i["name"]: i for i in original.get("indexes", [])}
        mod_idxs = {i["name"]: i for i in modified.get("indexes", [])}
        for i_name in orig_idxs:
            if i_name not in mod_idxs:
                q_idx = cls._quote_ident(i_name, engine)
                if engine == "sqlserver":
                    sql = f"DROP INDEX {q_idx} ON {tbl_name};"
                else:
                    sql = f"DROP INDEX {cls._quote_ident(schema, engine)}.{q_idx};"
                statements.append({
                    "sql": sql,
                    "destructive": True,
                    "description": f"Drop index {q_idx}",
                    "type": "indexes"
                })
        for i_name, idx in mod_idxs.items():
            if i_name not in orig_idxs:
                q_idx = cls._quote_ident(i_name, engine)
                fields = idx.get("fields", [])
                cols = []
                for f in fields:
                    if isinstance(f, dict):
                        col_str = cls._quote_ident(f["column"], engine)
                        if f.get("desc"):
                            col_str += " DESC"
                        cols.append(col_str)
                    else:
                        cols.append(cls._quote_ident(str(f), engine))
                unique_str = "UNIQUE " if idx.get("is_unique") else ""
                if engine == "sqlserver":
                    raw_itype = (idx.get("index_type") or "NONCLUSTERED").upper()
                    if raw_itype == "CLUSTERED":
                        itype = "NONCLUSTERED" if has_clustered else "CLUSTERED"
                        if itype == "CLUSTERED":
                            has_clustered = True
                    else:
                        itype = raw_itype
                    sql = f"CREATE {unique_str}{itype} INDEX {q_idx} ON {tbl_name} ({', '.join(cols)});"
                else:
                    itype = idx.get("index_type") or "BTREE"
                    sql = f"CREATE {unique_str}INDEX {q_idx} ON {tbl_name} USING {itype.lower()} ({', '.join(cols)});"
                statements.append({
                    "sql": sql,
                    "destructive": False,
                    "description": f"Create index {q_idx}",
                    "type": "indexes"
                })

        # 9. Triggers Diff
        orig_trigs = {t["name"]: t for t in original.get("triggers", [])}
        mod_trigs = {t["name"]: t for t in modified.get("triggers", [])}
        for t_name in orig_trigs:
            if t_name not in mod_trigs:
                q_tr = cls._quote_ident(t_name, engine)
                if engine == "sqlserver":
                    sql = f"DROP TRIGGER {cls._quote_ident(schema, engine)}.{q_tr};"
                else:
                    sql = f"DROP TRIGGER {q_tr} ON {tbl_name};"
                statements.append({
                    "sql": sql,
                    "destructive": True,
                    "description": f"Drop trigger {q_tr}",
                    "type": "triggers"
                })
        for t_name, tr in mod_trigs.items():
            if t_name not in orig_trigs or tr.get("definition") != orig_trigs[t_name].get("definition"):
                t_def = (tr.get("definition") or "").strip()
                if t_def:
                    statements.append({
                        "sql": t_def,
                        "destructive": False,
                        "description": f"Deploy trigger {t_name}",
                        "type": "triggers"
                    })

        # Build unified migration SQL string
        if not statements:
            migration_sql = ""
        elif engine == "sqlserver":
            migration_sql = "\n\nGO\n\n".join(s["sql"] for s in statements) + "\n\nGO\n"
        else:
            migration_sql = "\n\n".join(s["sql"] for s in statements) + "\n"

        return {
            "statements": statements,
            "migration_sql": migration_sql,
            "has_changes": bool(statements),
            "warnings": warnings,
            "has_destructive": any(s["destructive"] for s in statements)
        }
